### ISSUE TITLE
Build Graph Function Outputs and Slow Processing

### ISSUE THREAD

**Issue by stevenagl12** [vkola-lab/tmi2022#12]
Hi, we are trying to implement the graph-transformer code on our own data, and are having some issues with the time ti takes to run the build_graphs function and determining the validity of the outputs. We are running the function on our center for computational research nodes, but over the span of 24 hrs it only managed to get to the 9th patch. Additionally, we are assuming that the build_graphs function saves a c_idx.txt, adj_s.txt, and a features.pt for each and every patch. Is this true? Because if so, how do you get the function to finish when you have over 55000 image patches, and how do you handle the large amount of output data?

**Comment by GSWS** [comment]
1. build_graphs function saves a c_idx.txt, adj_s.txt, and a features.pt for each _WSI_, not each patch. 
2. Training a feature extractor using self-supervised learning takes a long time because augmentation is time-consuming. You could potentially use cosine similarity to find the positive pairs instead of augmentation. This will speed up training and increase sample diversity.
3. We provide a pre-trained <a href="https://drive.google.com/file/d/1JHwLqxg0RTNjQZXHqcSYnmLWVXiErulJ/view?usp=drive_link">model</a>.

**Comment by susuhu** [comment]
Calculating the adjacency matrices in two nested loops is extremely slow...
