### ISSUE TITLE
Inquiry about the Result and Feature Extractor

### ISSUE THREAD

**Issue by bryanwong17** [vkola-lab/tmi2022#3]
epoch [1/120] ------ train acc = 0.9183, val acc = 0.3571
================================
epoch [2/120] ------ train acc = 0.9712, val acc = 0.9762
================================
epoch [3/120] ------ train acc = 0.9567, val acc = 0.9762
================================
epoch [4/120] ------ train acc = 0.9423, val acc = 0.9762
================================
epoch [5/120] ------ train acc = 0.9712, val acc = 0.9762

Dear @vkola-lab,

I wonder is it okay if the val acc was not increasing starting from epoch 3 until the end?

Also, in order to acquire the patch feature extractor, do I need to divide the patches into training, val, and testing? because I combined all of the patches to create a feature extractor, and I'm concerned that using test data for training was considered cheating.

Thank you in advance!

**Comment by ghost** [comment]
epoch [1/120] ------ train acc = 0.9183, val acc = 0.3571
epoch [2/120] ------ train acc = 0.9712, val acc = 0.9762
epoch [3/120] ------ train acc = 0.9567, val acc = 0.9762
epoch [4/120] ------ train acc = 0.9423, val acc = 0.9762
epoch [5/120] ------ train acc = 0.9712, val acc = 0.9762

Dear @vkola-lab,

I wonder is it okay if the val acc was not increasing starting from epoch 3 until the end?

Also, in order to acquire the patch feature extractor, do I need to divide the patches into training, val, and testing? because I combined all of the patches to create a feature extractor, and I'm concerned that using test data for training was considered cheating.

Thank you in advance!

**Comment by nabilapuspit** [comment]
Hi, can you tell me how you organize the data for your training. I'm a bit confuse when its going to 

> --data_path "path_to_graph_data" \ #10
